In [10]:
import pandas as pd

In [13]:
import pandas as pd

try:
    df = pd.read_csv(r"E:\FIFA_World_Cup_Analytics\01_Raw_data\matches_1930_2022.csv")
    print("Dataset loaded successfully!")
    print(df.head())
except Exception as e:
    print(type(e).__name__)
    print(e)

Dataset loaded successfully!
   home_team away_team  home_score  home_xg  home_penalty  away_score  \
0  Argentina    France           3      3.3           4.0           3
1    Croatia   Morocco           2      0.7           NaN           1
2     France   Morocco           2      2.0           NaN           0
3  Argentina   Croatia           3      2.3           NaN           0
4    Morocco  Portugal           1      1.4           NaN           0

   away_xg  away_penalty      home_manager  home_captain  ...  \
0      2.2           2.0    Lionel Scaloni  Lionel Messi  ...
1      1.2           NaN      Zlatko Dalić   Luka Modrić  ...
2      0.9           NaN  Didier Deschamps   Hugo Lloris  ...
3      0.5           NaN    Lionel Scaloni  Lionel Messi  ...
4      0.9           NaN   Hoalid Regragui  Romain Saïss  ...

  home_penalty_shootout_miss_long  \
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN

                     away_penalty_shootout_miss_long  home_red_card  \
0  ['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...            NaN
1                                                NaN            NaN
2                                                NaN            NaN
3                                                NaN            NaN
4                                                NaN            NaN

  away_red_card   home_yellow_red_card away_yellow_red_card  \
0           NaN                    NaN                  NaN
1           NaN                    NaN                  NaN
2           NaN                    NaN                  NaN
3           NaN                    NaN                  NaN
4           NaN  Walid Cheddira · 90+3                  NaN

                               home_yellow_card_long  \
0  ['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...
1                                                NaN
2                                                NaN
3  ['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...
4  ['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...

                               away_yellow_card_long  \
0  ['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...
1  ['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...
2                  ['27&rsquor;|1:0|Sofiane Boufal']
3  ['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...
4                         ['87&rsquor;|1:0|Vitinha']

                             home_substitute_in_long  \
0  ['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...
1  ['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...
2  ['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...
3  ['62&rsquor;|2:0|Lisandro Martínez|for Leandro...
4  ['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...

                             away_substitute_in_long
0  ['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1  ['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2  ['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3  ['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',...
4  ['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

[5 rows x 44 columns]

In [14]:
df.head(5);

In [15]:
print(df.head())

   home_team away_team  home_score  home_xg  home_penalty  away_score  \
0  Argentina    France           3      3.3           4.0           3
1    Croatia   Morocco           2      0.7           NaN           1
2     France   Morocco           2      2.0           NaN           0
3  Argentina   Croatia           3      2.3           NaN           0
4    Morocco  Portugal           1      1.4           NaN           0

   away_xg  away_penalty      home_manager  home_captain  ...  \
0      2.2           2.0    Lionel Scaloni  Lionel Messi  ...
1      1.2           NaN      Zlatko Dalić   Luka Modrić  ...
2      0.9           NaN  Didier Deschamps   Hugo Lloris  ...
3      0.5           NaN    Lionel Scaloni  Lionel Messi  ...
4      0.9           NaN   Hoalid Regragui  Romain Saïss  ...

  home_penalty_shootout_miss_long  \
0                             NaN
1                             NaN
2                             NaN
3                             NaN
4                             NaN

                     away_penalty_shootout_miss_long  home_red_card  \
0  ['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...            NaN
1                                                NaN            NaN
2                                                NaN            NaN
3                                                NaN            NaN
4                                                NaN            NaN

  away_red_card   home_yellow_red_card away_yellow_red_card  \
0           NaN                    NaN                  NaN
1           NaN                    NaN                  NaN
2           NaN                    NaN                  NaN
3           NaN                    NaN                  NaN
4           NaN  Walid Cheddira · 90+3                  NaN

                               home_yellow_card_long  \
0  ['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...
1                                                NaN
2                                                NaN
3  ['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...
4  ['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...

                               away_yellow_card_long  \
0  ['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...
1  ['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...
2                  ['27&rsquor;|1:0|Sofiane Boufal']
3  ['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...
4                         ['87&rsquor;|1:0|Vitinha']

                             home_substitute_in_long  \
0  ['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...
1  ['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...
2  ['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...
3  ['62&rsquor;|2:0|Lisandro Martínez|for Leandro...
4  ['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...

                             away_substitute_in_long
0  ['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1  ['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2  ['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3  ['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',...
4  ['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

[5 rows x 44 columns]

In [16]:
type(df)

pandas.core.frame.DataFrame

In [17]:
df.shape

(964, 44)

In [18]:
df.head()

,home_team,away_team,home_score,home_xg,home_penalty,away_score,away_xg,away_penalty,home_manager,home_captain,...,home_penalty_shootout_miss_long,away_penalty_shootout_miss_long,home_red_card,away_red_card,home_yellow_red_card,away_yellow_red_card,home_yellow_card_long,away_yellow_card_long,home_substitute_in_long,away_substitute_in_long
0,Argentina,France,3,3.3,4.0,3,2.2,2.0,Lionel Scaloni,Lionel Messi,...,NaN,"['3|1:1|Kingsley Coman', '5|2:1|Aurélien Tchou...",NaN,NaN,NaN,NaN,"['45+7&rsquor;|2:0|Enzo Fernández', '90+8&rsqu...","['55&rsquor;|2:0|Adrien Rabiot', '87&rsquor;|2...",['64&rsquor;|2:0|Marcos Acuña|for Ángel Di Mar...,['41&rsquor;|2:0|Randal Kolo Muani|for Ousmane...
1,Croatia,Morocco,2,0.7,NaN,1,1.2,NaN,Zlatko Dalić,Luka Modrić,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"['69&rsquor;|2:1|Azzedine Ounahi', '84&rsquor;...",['61&rsquor;|2:1|Nikola Vlašić|for Andrej Kram...,['46&rsquor;|2:1|Ilias Chair|for Abdelhamid Sa...
2,France,Morocco,2,2.0,NaN,0,0.9,NaN,Didier Deschamps,Hugo Lloris,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,['27&rsquor;|1:0|Sofiane Boufal'],['65&rsquor;|1:0|Marcus Thuram|for Olivier Gir...,['21&rsquor;|1:0|Selim Amallah|for Romain Saïs...
3,Argentina,Croatia,3,2.3,NaN,0,0.5,NaN,Lionel Scaloni,Lionel Messi,...,NaN,NaN,NaN,NaN,NaN,NaN,"['68&rsquor;|2:0|Cristian Romero', '71&rsquor;...","['32&rsquor;|0:0|Mateo Kovačić', '32&rsquor;|0...",['62&rsquor;|2:0|Lisandro Martínez|for Leandro...,"['46&rsquor;|2:0|Mislav Oršić|for Borna Sosa',..."
4,Morocco,Portugal,1,1.4,NaN,0,0.9,NaN,Hoalid Regragui,Romain Saïss,...,NaN,NaN,NaN,NaN,Walid Cheddira · 90+3,NaN,"['70&rsquor;|1:0|Achraf Dari', '90+1&rsquor;|1...",['87&rsquor;|1:0|Vitinha'],['57&rsquor;|1:0|Achraf Dari|for Romain Saïss'...,['51&rsquor;|1:0|João Cancelo|for Raphaël Guer...

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 964 entries, 0 to 963
Data columns (total 44 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   home_team                        964 non-null    object
 1   away_team                        964 non-null    object
 2   home_score                       964 non-null    int64
 3   home_xg                          128 non-null    float64
 4   home_penalty                     35 non-null     float64
 5   away_score                       964 non-null    int64
 6   away_xg                          128 non-null    float64
 7   away_penalty                     35 non-null     float64
 8   home_manager                     964 non-null    object
 9   home_captain                     644 non-null    object
 10  away_manager                     964 non-null    object
 11  away_captain                     644 non-null    object
 12  Attendance                       964 non-null    int64
 13  Venue                            964 non-null    object
 14  Officials                        709 non-null    object
 15  Round                            964 non-null    object
 16  Date                             964 non-null    object
 17  Score                            964 non-null    object
 18  Referee                          709 non-null    object
 19  Notes                            73 non-null     object
 20  Host                             964 non-null    object
 21  Year                             964 non-null    int64
 22  home_goal                        718 non-null    object
 23  away_goal                        571 non-null    object
 24  home_goal_long                   718 non-null    object
 25  away_goal_long                   571 non-null    object
 26  home_own_goal                    39 non-null     object
 27  away_own_goal                    17 non-null     object
 28  home_penalty_goal                116 non-null    object
 29  away_penalty_goal                84 non-null     object
 30  home_penalty_miss_long           6 non-null      object
 31  away_penalty_miss_long           9 non-null      object
 32  home_penalty_shootout_goal_long  34 non-null     object
 33  away_penalty_shootout_goal_long  34 non-null     object
 34  home_penalty_shootout_miss_long  24 non-null     object
 35  away_penalty_shootout_miss_long  30 non-null     object
 36  home_red_card                    51 non-null     object
 37  away_red_card                    54 non-null     object
 38  home_yellow_red_card             23 non-null     object
 39  away_yellow_red_card             31 non-null     object
 40  home_yellow_card_long            621 non-null    object
 41  away_yellow_card_long            627 non-null    object
 42  home_substitute_in_long          740 non-null    object
 43  away_substitute_in_long          747 non-null    object
dtypes: float64(4), int64(4), object(36)
memory usage: 331.5+ KB

In [20]:
df.isnull().sum()

home_team                            0
away_team                            0
home_score                           0
home_xg                            836
home_penalty                       929
away_score                           0
away_xg                            836
away_penalty                       929
home_manager                         0
home_captain                       320
away_manager                         0
away_captain                       320
Attendance                           0
Venue                                0
Officials                          255
Round                                0
Date                                 0
Score                                0
Referee                            255
Notes                              891
Host                                 0
Year                                 0
home_goal                          246
away_goal                          393
home_goal_long                     246
away_goal_long                     393
home_own_goal                      925
away_own_goal                      947
home_penalty_goal                  848
away_penalty_goal                  880
home_penalty_miss_long             958
away_penalty_miss_long             955
home_penalty_shootout_goal_long    930
away_penalty_shootout_goal_long    930
home_penalty_shootout_miss_long    940
away_penalty_shootout_miss_long    934
home_red_card                      913
away_red_card                      910
home_yellow_red_card               941
away_yellow_red_card               933
home_yellow_card_long              343
away_yellow_card_long              337
home_substitute_in_long            224
away_substitute_in_long            217
dtype: int64

In [21]:
df.duplicated().sum()

np.int64(0)

In [25]:
df.columns

Index(['home_team', 'away_team', 'home_score', 'home_xg', 'home_penalty',
       'away_score', 'away_xg', 'away_penalty', 'home_manager', 'home_captain',
       'away_manager', 'away_captain', 'Attendance', 'Venue', 'Officials',
       'Round', 'Date', 'Score', 'Referee', 'Notes', 'Host', 'Year',
       'home_goal', 'away_goal', 'home_goal_long', 'away_goal_long',
       'home_own_goal', 'away_own_goal', 'home_penalty_goal',
       'away_penalty_goal', 'home_penalty_miss_long', 'away_penalty_miss_long',
       'home_penalty_shootout_goal_long', 'away_penalty_shootout_goal_long',
       'home_penalty_shootout_miss_long', 'away_penalty_shootout_miss_long',
       'home_red_card', 'away_red_card', 'home_yellow_red_card',
       'away_yellow_red_card', 'home_yellow_card_long',
       'away_yellow_card_long', 'home_substitute_in_long',
       'away_substitute_in_long'],
      dtype='object')

In [26]:
#DATASET->2

In [27]:
world_cup = pd.read_csv(r"E:\FIFA_World_Cup_Analytics\01_Raw_data\world_cup.csv")

In [28]:
world_cup.head()

,Year,Host,Teams,Champion,Runner-Up,TopScorrer,Attendance,AttendanceAvg,Matches
0,2022,Qatar,32,Argentina,France,Kylian Mbappé - 8,3404252,53191,64
1,2018,Russia,32,France,Croatia,Harry Kane - 6,3031768,47371,64
2,2014,Brazil,32,Germany,Argentina,James Rodríguez - 6,3429873,53592,64
3,2010,South Africa,32,Spain,Netherlands,"Wesley Sneijder, Thomas Müller... - 5",3178856,49670,64
4,2006,Germany,32,Italy,France,Miroslav Klose - 5,3352605,52384,64

In [29]:
world_cup.shape

(22, 9)

In [30]:
world_cup.columns

Index(['Year', 'Host', 'Teams', 'Champion', 'Runner-Up', 'TopScorrer',
       'Attendance', 'AttendanceAvg', 'Matches'],
      dtype='object')

In [31]:
world_cup.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22 entries, 0 to 21
Data columns (total 9 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           22 non-null     int64
 1   Host           22 non-null     object
 2   Teams          22 non-null     int64
 3   Champion       22 non-null     object
 4   Runner-Up      22 non-null     object
 5   TopScorrer     22 non-null     object
 6   Attendance     22 non-null     int64
 7   AttendanceAvg  22 non-null     int64
 8   Matches        22 non-null     int64
dtypes: int64(5), object(4)
memory usage: 1.7+ KB

In [32]:
world_cup.duplicated().sum()

np.int64(0)

In [33]:
#Dataset->3

In [35]:
ranking_2022 = pd.read_csv(r"E:\FIFA_World_Cup_Analytics\01_Raw_data\fifa_ranking_2022-10-06.csv")

In [36]:
ranking_2022.head()

,team,team_code,association,rank,previous_rank,points,previous_points
0,Brazil,BRA,CONMEBOL,1,1,1841.30,1837.56
1,Belgium,BEL,UEFA,2,2,1816.71,1821.92
2,Argentina,ARG,CONMEBOL,3,3,1773.88,1770.65
3,France,FRA,UEFA,4,4,1759.78,1764.85
4,England,ENG,UEFA,5,5,1728.47,1737.46

In [37]:
ranking_2022.columns

Index(['team', 'team_code', 'association', 'rank', 'previous_rank', 'points',
       'previous_points'],
      dtype='object')

In [38]:
ranking_2022.shape

(211, 7)

In [39]:
ranking_2022.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 7 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team             211 non-null    object
 1   team_code        211 non-null    object
 2   association      211 non-null    object
 3   rank             211 non-null    int64
 4   previous_rank    211 non-null    int64
 5   points           211 non-null    float64
 6   previous_points  211 non-null    float64
dtypes: float64(2), int64(2), object(3)
memory usage: 11.7+ KB

In [40]:
ranking_2022.duplicated().sum()

np.int64(0)

In [41]:
#Dataset->4

In [42]:
ranking_2026 = pd.read_csv(r"E:\FIFA_World_Cup_Analytics\01_Raw_data\fifa_ranking_2026-06-08.csv")

In [46]:
ranking_2026.head()

,team,team_code,association,rank,previous_rank,points,previous_points,rated_matches
0,Argentina,ARG,CONMEBOL,1,3,1876.118331,1874.814835,59
1,Spain,ESP,UEFA,2,2,1873.013187,1876.395199,56
2,France,FRA,UEFA,3,1,1869.428449,1877.322731,57
3,England,ENG,UEFA,4,4,1827.048678,1825.965482,57
4,Portugal,POR,UEFA,5,5,1766.177547,1763.834406,56

In [48]:
ranking_2026.shape

(211, 8)

In [50]:
ranking_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 211 entries, 0 to 210
Data columns (total 8 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   team             211 non-null    object
 1   team_code        211 non-null    object
 2   association      211 non-null    object
 3   rank             211 non-null    int64
 4   previous_rank    211 non-null    int64
 5   points           211 non-null    float64
 6   previous_points  211 non-null    float64
 7   rated_matches    211 non-null    int64
dtypes: float64(2), int64(3), object(3)
memory usage: 13.3+ KB

In [51]:
ranking_2026.duplicated().sum()

np.int64(0)

In [52]:
#Dataset--> 5

In [55]:
schedule_2026 = pd.read_csv(
    r"E:\FIFA_World_Cup_Analytics\01_Raw_data\schedule_2026.csv"
)

In [56]:
schedule_2026.head()

,Round,Day,Date,Time,Score,Referee,Notes,Year,home_team,away_team
0,Group stage,Thu,2026-06-11,13:00 (22:00),NaN,NaN,NaN,2026,Mexico,South Africa
1,Group stage,Thu,2026-06-11,20:00 (05:00),NaN,NaN,NaN,2026,Korea Republic,Czechia
2,Group stage,Fri,2026-06-12,15:00 (22:00),NaN,NaN,NaN,2026,Canada,Bosnia-Herzegovina
3,Group stage,Fri,2026-06-12,18:00 (04:00),NaN,NaN,NaN,2026,United States,Paraguay
4,Group stage,Sat,2026-06-13,12:00 (22:00),NaN,NaN,NaN,2026,Qatar,Switzerland

In [57]:
schedule_2026.shape

(72, 10)

In [58]:
schedule_2026.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 72 entries, 0 to 71
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Round      72 non-null     object
 1   Day        72 non-null     object
 2   Date       72 non-null     object
 3   Time       72 non-null     object
 4   Score      0 non-null      float64
 5   Referee    0 non-null      float64
 6   Notes      0 non-null      float64
 7   Year       72 non-null     int64
 8   home_team  72 non-null     object
 9   away_team  72 non-null     object
dtypes: float64(3), int64(1), object(6)
memory usage: 5.8+ KB

In [59]:
schedule_2026.columns

Index(['Round', 'Day', 'Date', 'Time', 'Score', 'Referee', 'Notes', 'Year',
       'home_team', 'away_team'],
      dtype='object')

In [60]:
schedule_2026.isnull().sum()

Round         0
Day           0
Date          0
Time          0
Score        72
Referee      72
Notes        72
Year          0
home_team     0
away_team     0
dtype: int64

In [64]:
schedule_2026.duplicated().sum()

np.int64(0)